# Generated by Django 2.1.2 on 2018-10-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('POST', 'Post'), ('RETWEET', 'Retweet'), ('VIDEO', 'Video')], default='Post', max_length=32)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
