# Generated by Django 2.1.2 on 2018-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('post', 'Post'), ('post', 'Retweet'), ('video', 'Video')], max_length=20)),
                ('body', models.TextField(max_length=400)),
                ('slug', models.SlugField(unique=True)),
                ('tweet_owner', models.CharField(max_length=100)),
                ('tweet_id', models.CharField(max_length=32)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
