# Generated by Django 2.1.2 on 2018-11-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181103_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweet_body',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tweet_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tweet_owner_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tweet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweet_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
