# Generated by Django 2.1.2 on 2018-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181103_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweet_owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
