# Generated by Django 2.1.2 on 2018-11-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181104_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tweet_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
